# contentDir = 'content/en'
disabled = false
languageCode = 'sq-AL'
languageName = 'Albanian'
title = 'Erva Kambo' # This will go in the Header as well
copyright = "Â© 2024 all rights reserved - Designed by Ludovico Caluori ðŸŽ¨"
contentDir = "content/sq"

# Change single params to false to remove from rendering
[params]
  subtitle = "Psikologe" # This goes in the header and in the site title

  # PAGES
  [params.homepage]
    preTitle = 'Psikologe nÃ« Firence'
    title = "Erva Kambo"
    intro= """TÃ« duhet tÃ« luftosh pÃ«r tÃ« qÃ«nÃ« vetvetja nÃ« njÃ« shoqÃ«ri qÃ« ndihet sikur nuk Ã«shtÃ« menduar pÃ«r ty? A
    ke vÃ«shtirÃ«si pÃ«r tÃ« kuptuar ose emÃ«rtuar ndjenjat, nevojat dhe dÃ«shirat e tua? Ndoshta ndihesh i
    padÃ«gjuar, i padukshÃ«m ose ndihesh sikur duhet tÃ« fshehÃ«sh disa pjesÃ« tÃ« vehtes nÃ« mÃ«nyrÃ« qÃ« tÃ«
    pranohesh nga tÃ« tjerÃ«t? Ã‹shtÃ« e vÃ«shtirÃ« tÃ« ndihesh mirÃ« kur ndihesh i zbrazur dhe i mbingarkuar.
    **Stresi, trauma** dhe **humbja e njÃ« personi tÃ« dashur** mund tÃ« ta vÃ«shtirÃ«sojnÃ« jetÃ«n e pÃ«rditshme
    dhe nÃ« tÃ« njÃ«jtÃ«n kohÃ« tÃ« tÃ« sfidojnÃ« me probleme si **ankthi e depresioni**.
    Terapia Ã«shtÃ« ura qÃ« lidh betejat tona individuale me kujdesin ndaj vehtes dhe tÃ« tjerÃ«ve. Mbajtja e
    marrÃ«dhÃ«nieve, arritja e qÃ«llimeve madje dhe pÃ«rjetimi i gÃ«zimit, shpesh mund tÃ« ndihen si njÃ«
    betejÃ« e vÃ«shtirÃ« nÃ« njÃ« botÃ« shtypÃ«se, dhe pesha e shtypjes mund tÃ« na izolojÃ« nga vetja dhe tÃ«
    tjerÃ«t. PavarÃ«sisht sfidave qÃ« jeta tÃ« ka sjellÃ« kohÃ«t e fundit, nuk ke pse tÃ« mbetesh kÃ«tu. VetÃ«m ti
    mund tÃ« kurosh tÃ« gjitha pjesÃ«t e tua dhe tÃ« rifitosh ndjenjÃ«n e tÃ«rÃ«sisÃ« dhe tÃ« dinjitetit. Nuk je
    vetÃ«m!
        """
    mainButton = "Kontakto"
    mainButtonRef = "https://wa.me/393801783513"
    [params.homepage.description]
    enabled = true
    # You can use some markdown safely for the description as long as you don't include line breaks
    secondTitle = "Njihuni me Erva Kambo, Psikologe"
    paragraph = """MÃ« pÃ«lqen ti ndihmoj njerÃ«zit tÃ« ndihen tÃ« kuptuar, tÃ« pÃ«rballen me dhimbjen dhe gÃ«zimin, dhe tÃ«
    gjejnÃ« forcÃ« tÃ« brÃ«ndshme nÃ« momente tÃ« vÃ«shtira tÃ« jetÃ«s sÃ« tyre. NÃ«pÃ«rmjet njÃ« marrÃ«dhÃ«nieje tÃ«
    bazuar nÃ« besim dhe ndjeshmÃ«ri, do tÃ« jetÃ« e mundur tÃ« krijojmÃ« njÃ« hapÃ«sirÃ« tÃ« sigurt nÃ« tÃ« cilÃ«n do
    tÃ« kesh mundÃ«sinÃ« tÃ« zbulosh thellÃ«sisht vehten dhe tÃ« zhvillosh njÃ« ndÃ«rgjegjÃ«sim mÃ« tÃ« madh
    pÃ«r emocionet, mendimet dhe sjelljet e tua. BashkÃ« do tÃ« eksplorojmÃ« Ã§Ã«shtje dhe probleme qÃ«
    lidhen me familjen, punÃ«n, identitetin, gjininÃ« dhe kulturÃ«n. UnÃ« mund tÃ« tÃ« ndihmoj tÃ« lÃ«vizÃ«sh
    drejt njÃ« versioni tÃ« jetÃ«s tÃ«nde ku shqetÃ«simi emocional dhe fizik nuk diktojnÃ« mÃ« vendimet e tua.
    Bashkohu me mua nÃ« njÃ« proces zbulimi dhe rritjeje!"""
    paragraph2= "Ofroj shÃ«rbime nÃ« italisht, anglisht dhe shqip!"

[params.office]
 title = "Zyra"
 description = "Do tÃ« gjeni njÃ« zyrÃ« mikpritÃ«se nÃ« qendÃ«r tÃ« Firences."
 buttonText = "UdhÃ«zime" 
 buttonLink = "https://maps.app.goo.gl/fxmD9cQXUVS5Xp9t8" # google maps share link here (for button)
 mapLink = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d23046.70708393103!2d11.250820486945312!3d43.77621354501747!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x132a54126faf8b3d%3A0x37e724bfc089c27a!2sVia%20dei%20della%20Robbia%2C%2023%2C%2050132%20Firenze%20FI!5e0!3m2!1sit!2sit!4v1714143516043!5m2!1sit!2sit" # google maps embed link here

[params.contacts]
  title = "Rezervoni njÃ« takim tani!"
  formCallToAction = ""
  socialCallToAction = "MÃ« kontaktoni nÃ« rrjetet sociale mÃ« poshtÃ«. Mos ngurroni tÃ« mÃ« shkruani nÃ« Whatsapp!"
  [params.contacts.form]
    firstname = "Emri*"
    lastname = "Mbiemri*"
    email = "E-mail*"
    phone = "Telefon*"
    Inquiry = "KÃ«rkesa juaj*"
    checkbox = "PÃ«rpunimi i tÃ« dhÃ«nave nÃ« pajtim me ligjin*"
    submitBtn = "DÃ‹RGO"

[params.services]
  title = "ShÃ«rbimet"
  description = """ Ofroj mbÃ«shtetje psikologjike dhe kÃ«shillim individual dhe nÃ« Ã§ift. Me qasjen time tÃ«
orientimit konjitiv - sjellÃ«s i pÃ«rkushtohem mendjes, ndjenjave dhe praktikave tÃ« mirÃ«qenies.
Seancat tona do tÃ« zgjasin 60 minuta personalisht ose online. SÃ« bashku do mund tÃ« punojmÃ« nÃ« fushat e mÃ«poshtme:"""
  [params.services.list]
    # You can add as much params.services.list.N as you like
    [params.services.list.0]
      title= "Promovimi i mirÃ«qÃ«nies dhe i vetÃ«vlerÃ«simit"
      description= ""
    [params.services.list.01]
      title = "Rritja personale dhe vetÃ«-zbulimi"
      description= ""
    [params.services.list.02]
      title = "PÃ«rmirÃ«simi i marrÃ«dhÃ«nieve dhe i aftÃ«sive tÃ« komunikimit"
      description= ""
    [params.services.list.03]
      title = "Ankth dhe depresion"
      description= ""
    [params.services.list.04]
      title = "VÃ«shtirÃ«si nÃ« sjellje"
      description= ""
    [params.services.list.05]
      title = "VarÃ«sia emocionale"
      description= ""
    [params.services.list.06]
      title = "Menaxhimi i stresit dhe ndÃ«rtimi i qÃ«ndrueshmÃ«risÃ«"
      description= ""
    [params.services.list.07]
      title = "PÃ«rmirÃ«simi i performancÃ«s dhe arritja e qÃ«llimeve"
      description= ""
    [params.services.list.08]
      title = "PÃ«rpunimi i humbjes dhe pÃ«rballja me traumÃ«n"
      description= ""
    [params.services.list.09]
      title = "Menaxhimi i stresit dhe krizat personale"
      description= ""
    [params.services.list.10]
      title = "â€œMÃ«rgimi dhe jeta jashtÃ« shtetitâ€"
      description= ""
  
# /. PAGES

[params.socials]
  enabled = true # enables/disables the whole social section
  callToAction= "Lidhu me mua nÃ« rrjetet sociale >"
      [[params.socials.link]]
        name = "instagram"
        link = "https://www.instagram.com/ervakambo/"
      [[params.socials.link]]
        name = "linkedin"
        link = "https://www.linkedin.com/in/erva-kambo"
      [[params.socials.link]]
        name = "whatsapp"
        link = "https://wa.me/393801783513"
      # You can add other socials here by copypasting the above section and
      # selecting the right name for the icon from here https://icons.getbootstrap.com/

[params.schedules]
  enabledFooter = false # This will add the schedules on the footer too
  enabledContacts = true
  title = "Oraret" # For contacts page only
  [params.schedules.days]
  # Use something like "Monday: 9-13" for each day
  # if left empty it is disabled (default)
    day1 = "E HÃ«nÃ«: 9:00 - 19:00"
    day2 = "E MartÃ«: 9:00 - 19:00"
    day3 = "E MÃ«rkurÃ«: 9:00 - 19:00"
    day4 = "E Enjte: 9:00 - 19:00"
    day5 = "E Premte: 9:00 - 19:00"
    day6 = ""
    day7 = ""

[params.footer]
  extraDescription = "Urdhri i PsikologÃ«ve tÃ« ToskanÃ«s Nr. 10278"
  vat = "TVSH 07339790482"
  [params.footer.navigate]
  heading = "Navigoni"   
  [params.footer.contacts]
  enabled = true # enables/disables the whole contacts section
  heading = "kontakt"
  address = "Via della Robbia 23 50132, Firenze"
  mail = "psicologa.kambo@gmail.com"
  mail2 = "erva.kambo@psypec.it"
  phone = "+39 3801783513"
  
 
[menus]
# If you add a new language remember to change the pageRef to match the desired content folder!
  [[menus.main]]
  name = "Kryefaqja"
  pageRef = "/"
  weight = 1
  [[menus.main]]
  name = "ShÃ«rbimet"
  pageRef = "/services"
  weight = 2
  [[menus.main]]
  name = "Zyra"
  pageRef = "/office"
  weight = 3
  [[menus.main]]
  name = "Kontaktet"
  pageRef = "/contacts"
  weight = 4